all:
  vars:
    ansible_user: isucon
    ansible_ssh_private_key_file: /Users/chakku/.ssh/id_rsa
    ansible_python_interpreter: /usr/bin/python3 # TODO check
  hosts:
    s1:
      ansible_host: 52.192.15.187
    s2:
      ansible_host: 52.198.174.209
    s3:
      ansible_host: 52.69.82.110
        #  children:
        #    docker:
        #      hosts:
        #        isuansible:
        #          ansible_connection: docker
