all:
  vars:
    ansible_user: # TODO edit
    ansible_ssh_private_key_file:  # TODO edit
    ansible_python_interpreter: /usr/bin/python3 # TODO check
  hosts:
    s1:
      ansible_host: # TODO edit
    s2:
      ansible_host: # TODO edit
    s3:
      ansible_host: # TODO edit
  children:
    docker:
      hosts:
        isuansible:
          ansible_connection: docker
